services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: express-api
    restart: always
    environment:
      DATABASE_URL: mongodb://root:password@mongodb:27017/your-database?authSource=admin
      NODE_ENV: production
      PORT: 8000
    volumes:
      # Development mode: Uncomment (both) for hot-reloading
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    expose:
      - '8000'
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  mongo-data:
